document.addEventListener('DOMContentLoaded', function() {
    const mysteriesList = document.getElementById('mysteries-list');
    const mysteries = [
        "La Joconde de Léonard de Vinci cache un sourire mystérieux.",
        "Les lignes de Nazca au Pérou sont visibles seulement depuis le ciel.",
        "La disparition de l'artiste Banksy garde son identité secrète et ajoute à son mystère.",
        "Les pyramides d'Égypte ont été construites par des civilisations anciennes, mais la méthode exacte reste un mystère.",
        "La signification des dessins rupestres de Lascaux en France est encore débattue par les archéologues.",
        "Le visage de la Statue de la Liberté est basé sur celui de la mère de l'ingénieur Gustave Eiffel.",
        "Le code secret du manuscrit de Voynich, un livre ancien rempli d'illustrations et de texte inconnu, n'a pas encore été déchiffré.",
        "Les peintures rupestres de la grotte Chauvet en France ont des milliers d'années, mais leur signification exacte est encore inconnue.",
        "La construction des statues de l'île de Pâques reste un mystère, car il n'y a pas de consensus sur la façon dont elles ont été déplacées.",
        "Les gravures énigmatiques sur la stèle de Droit Divin à Göbekli Tepe en Turquie laissent les archéologues perplexes quant à leur signification.",
        "Les disques de Phaistos, des artefacts en argile trouvés en Crète, contiennent une écriture inconnue qui n'a pas encore été déchiffrée.",
        "Le Codex Seraphinianus est un livre étrange et mystérieux écrit dans une langue fictive et rempli d'illustrations étranges.",
        "Le mystère de la construction de Stonehenge, avec ses pierres massives disposées en un cercle, continue de fasciner les archéologues.",
        "La nature exacte de la relation entre les motifs dans les peintures de la grotte d'Altamira en Espagne et la spiritualité préhistorique reste inconnue.",
        "La signification des dessins géométriques sur le sol de la cathédrale de Chartres en France est encore un mystère pour les historiens de l'art.",
        "Les figures énigmatiques du triskèle de Newgrange en Irlande laissent les archéologues perplexes quant à leur signification exacte.",
        "Les figures en forme de spirale trouvées sur des sites néolithiques comme Skara Brae en Écosse restent un mystère quant à leur signification.",
        "Les lignes et les géoglyphes de la plaine de Nazca au Pérou ont suscité de nombreuses théories sur leur but et leur signification.",
        "La signification exacte des masques énigmatiques de la culture olmèque du Mexique précolombien reste inconnue.",
        "Les dessins énigmatiques trouvés sur les vases grecs anciens ont été interprétés de différentes manières par les historiens de l'art.",
        "La signification des sculptures mégalithiques trouvées à Göbekli Tepe en Turquie reste un mystère pour les archéologues.",
        "La signification des symboles et des dessins sur les murs de la tombe de Nefertari dans la vallée des reines en Égypte reste un mystère.",
        "Les motifs géométriques et les symboles sur les textiles paracas anciens du Pérou ont été interprétés de différentes manières par les archéologues.",
        "Les mystérieux motifs en spirale trouvés sur les céramiques de la culture de Vinča en Europe préhistorique continuent de susciter des débats.",
        "Les motifs énigmatiques sur les pierres runiques vikings ont été interprétés de différentes manières par les chercheurs.",
        "Les sculptures en pierre énigmatiques de la civilisation de Sanxingdui en Chine ancienne ont été découvertes récemment et leur signification reste un mystère.",
        "Les dessins étranges sur les disques en or de la civilisation de Sican au Pérou précolombien ont suscité de nombreuses théories sur leur signification.",
        "Les motifs géométriques sur les textiles de la culture de Paracas au Pérou ancien ont suscité de nombreuses théories sur leur signification culturelle.",
        "Les peintures énigmatiques des tombes étrusques en Italie ancienne ont été interprétées de différentes manières par les historiens de l'art.",
        "Les dessins énigmatiques sur les vases peints de la Grèce antique ont été interprétés de différentes manières par les archéologues.",
        "Les sculptures en bois énigmatiques de la culture de Shigir en Sibérie ancienne ont été découvertes récemment et leur signification reste un mystère.",
        "Les motifs énigmatiques sur les textiles de la civilisation de Chachapoyas au Pérou ancien ont suscité de nombreuses théories sur leur signification.",
        "Les motifs géométriques étranges sur les textiles de la culture de Wari en Amérique du Sud ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les motifs énigmatiques sur les céramiques de la civilisation de Moche au Pérou ancien ont suscité de nombreuses théories sur leur signification.",
        "Les motifs énigmatiques sur les textiles de la civilisation de Chimu au Pérou ancien ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux dessins en spirale trouvés sur les artefacts de la culture de Vinča en Europe préhistorique continuent de susciter des débats sur leur signification.",
        "Les mystérieux géoglyphes de la culture de Paracas au Pérou ancien ont été découverts récemment et leur signification exacte reste un mystère.",
        "Les motifs énigmatiques sur les textiles de la culture de Nazca au Pérou ancien ont été interprétés de différentes manières par les archéologues.",
        "Les motifs énigmatiques sur les textiles de la civilisation de Tiwanaku en Amérique du Sud ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Qijia en Chine ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux géoglyphes de la civilisation de Cahuachi au Pérou ancien ont été découverts récemment et leur signification exacte reste un mystère.",
        "Les motifs énigmatiques sur les céramiques de la culture de Jeulmun en Corée ancienne ont été interprétés de différentes manières par les archéologues.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Karasuk en Sibérie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Longshan en Chine ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Yangshao en Chine ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Jōmon au Japon ancien ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Cucuteni-Trypillia en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Bell Beaker en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Lepenski Vir en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Vinča en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Trypillia en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Sredny Stog en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Samarra en Mésopotamie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Halaf en Mésopotamie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Cucuteni-Trypillia en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Corded Ware en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Samara en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Sintashta-Petrovka en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture d'Abashevo en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Yaz en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Poltavka en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Fatyanovo-Balanovo en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture d'Afanasievo en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Yamna en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Srubna en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture d'Andronovo en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Karasuk en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Glazkov en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture d'Okunevo en Russie ancienne ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Comb Ware en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Decea Mureșului en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Tiszapolgár en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Funnelbeaker en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Cortaillod en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Cucuteni en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Baden en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Globular Amphora en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Yamna en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Srubna en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture d'Andronovo en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture d'Abashevo en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Sintashta en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Poltavka en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Seima-Turbino en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Okunevo en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Afanasievo en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Fatyanovo-Balanovo en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Yamnaya en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Glazkov en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Balanovo en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Usatovo en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Catacomb en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Cotofeni en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Babyno en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Zimnicea en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de  Noua en Europe préhistorique ont suscité de nombreuses théories sur leur signification.",
        "Les mystérieux motifs en spirale trouvés sur les artefacts de la culture de Coțofeni en Europe préhistorique ont suscité de nombreuses théories sur leur signification."
    ];

    mysteries.forEach((mystery, index) => {
        const listItem = document.createElement('li');
        listItem.textContent = `${index + 1}. ${mystery}`; // Ajout de "${index + 1}. " pour numéroter chaque mystère
        mysteriesList.appendChild(listItem);
    });
    });

